/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as AuthImport } from './routes/_auth';
import { Route as AuthLoginImport } from './routes/_auth/login';
import { Route as AuthRegisterImport } from './routes/_auth/register';
import { Route as AuthenticatedImport } from './routes/_authenticated';
import { Route as AuthenticatedDashboardIndexImport } from './routes/_authenticated/dashboard/index';
import { Route as AuthenticatedDashboardTodosIndexImport } from './routes/_authenticated/dashboard/todos/index';
import { Route as AuthenticatedDashboardTodosNewImport } from './routes/_authenticated/dashboard/todos/new';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any);

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any);

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any);

const AuthenticatedDashboardIndexRoute = AuthenticatedDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedDashboardTodosIndexRoute = AuthenticatedDashboardTodosIndexImport.update({
  id: '/dashboard/todos/',
  path: '/dashboard/todos/',
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedDashboardTodosNewRoute = AuthenticatedDashboardTodosNewImport.update({
  id: '/dashboard/todos/new',
  path: '/dashboard/todos/new',
  getParentRoute: () => AuthenticatedRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthenticatedImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/login': {
      id: '/_auth/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof AuthLoginImport;
      parentRoute: typeof AuthImport;
    };
    '/_auth/register': {
      id: '/_auth/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof AuthRegisterImport;
      parentRoute: typeof AuthImport;
    };
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
    '/_authenticated/dashboard/todos/new': {
      id: '/_authenticated/dashboard/todos/new';
      path: '/dashboard/todos/new';
      fullPath: '/dashboard/todos/new';
      preLoaderRoute: typeof AuthenticatedDashboardTodosNewImport;
      parentRoute: typeof AuthenticatedImport;
    };
    '/_authenticated/dashboard/todos/': {
      id: '/_authenticated/dashboard/todos/';
      path: '/dashboard/todos';
      fullPath: '/dashboard/todos';
      preLoaderRoute: typeof AuthenticatedDashboardTodosIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute;
  AuthenticatedDashboardTodosNewRoute: typeof AuthenticatedDashboardTodosNewRoute;
  AuthenticatedDashboardTodosIndexRoute: typeof AuthenticatedDashboardTodosIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardTodosNewRoute: AuthenticatedDashboardTodosNewRoute,
  AuthenticatedDashboardTodosIndexRoute: AuthenticatedDashboardTodosIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '': typeof AuthenticatedRouteWithChildren;
  '/login': typeof AuthLoginRoute;
  '/register': typeof AuthRegisterRoute;
  '/dashboard': typeof AuthenticatedDashboardIndexRoute;
  '/dashboard/todos/new': typeof AuthenticatedDashboardTodosNewRoute;
  '/dashboard/todos': typeof AuthenticatedDashboardTodosIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '': typeof AuthenticatedRouteWithChildren;
  '/login': typeof AuthLoginRoute;
  '/register': typeof AuthRegisterRoute;
  '/dashboard': typeof AuthenticatedDashboardIndexRoute;
  '/dashboard/todos/new': typeof AuthenticatedDashboardTodosNewRoute;
  '/dashboard/todos': typeof AuthenticatedDashboardTodosIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/_auth': typeof AuthRouteWithChildren;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/_auth/login': typeof AuthLoginRoute;
  '/_auth/register': typeof AuthRegisterRoute;
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute;
  '/_authenticated/dashboard/todos/new': typeof AuthenticatedDashboardTodosNewRoute;
  '/_authenticated/dashboard/todos/': typeof AuthenticatedDashboardTodosIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/todos/new'
    | '/dashboard/todos';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/todos/new'
    | '/dashboard/todos';
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/todos/new'
    | '/_authenticated/dashboard/todos/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_authenticated"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/register"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard/",
        "/_authenticated/dashboard/todos/new",
        "/_authenticated/dashboard/todos/"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/todos/new": {
      "filePath": "_authenticated/dashboard/todos/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/todos/": {
      "filePath": "_authenticated/dashboard/todos/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
