name = "api"
main = "src/index.ts"
compatibility_date = "2025-04-02"
compatibility_flags = ["nodejs_compat"]

vars = { ENV = "development" }

[[d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "1dbd51fc-6ee7-4fc4-96ec-4ed829b29880"
migrations_dir = "../../packages/database/migrations"

[assets]
directory = "public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[observability]
enabled = true
logs = { enabled = true }

[env.preview]
vars = { ENV = "preview" }
d1_databases = [
  { binding = "DB", database_name = "dev-db", database_id = "1dbd51fc-6ee7-4fc4-96ec-4ed829b29880" },
]

[env.production]
vars = { ENV = "production" }
d1_databases = [
  { binding = "DB", database_name = "dev-db", database_id = "1dbd51fc-6ee7-4fc4-96ec-4ed829b29880" },
]
